#!/bin/sh

TARGET="$1"
TAG="$2"

if [ "${TARGET}" = "" ]
then
	echo need target
	exit -1
fi

cp ./bin/* ${TARGET}/bin
cp -R ./script/* ${TARGET}/bin
cp -R ./templates ${TARGET}/
cp -R ./exfe.json.example ${TARGET}/
cp -R ./configure ${TARGET}/
cp ./launch ${TARGET}/

cd ${TARGET}
git add .
git commit -m "${TAG}" || echo "no commit"
