#!/bin/sh

TARGET="$1"
TAG="$2"

if [ "${TARGET}" = "" ]
then
	echo need target
	exit -1
fi

rm -Rf ${TARGET}/bin/* ${TARGET}/templates
cp -f ./bin/* ${TARGET}/bin
cp -Rf ./script/* ${TARGET}/bin
cp -Rf ./templates ${TARGET}/
cp -Rf ./exfe.json.example ${TARGET}/
cp -Rf ./configure ${TARGET}/
cp -f ./launch ${TARGET}/
[ -e ./lighttpd-1.4.28/src/.lib/mod_mysql_obj.so ] && cp -f ./lighttpd-1.4.28/src/.lib/mod_mysql_obj.so ${TARGET}

cd ${TARGET}
git add -u
git add .
git commit -m "${TAG}" || echo "no commit"
