#!/bin/sh

TARGET="$1"
TAG="$2"

if [ "${TARGET}" = "" ]
then
	echo need target
	exit -1
fi

rm -Rf ${TARGET}/bin/* ${TARGET}/templates
cp -f ./bin/* ${TARGET}/bin
cp -Rf ./script/* ${TARGET}/bin
cp -Rf ./templates ${TARGET}/
cp -Rf ./exfe.json.example ${TARGET}/
cp -Rf ./configure ${TARGET}/
cp -f ./launch ${TARGET}/

cd ${TARGET}
git add -u
git add .
git commit -m "${TAG}" || echo "no commit"
