#!/bin/sh

if [ "$1" = "" ]
then
	vimdiff exfe.json exfe.json.example
	git add exfe.json
	git commit -m "update"
fi

for i in service queue bot
do
	service exfe_$i stop
done

git checkout -f HEAD

for i in service queue bot
do
	service exfe_$i start
done
