#!/bin/sh

if [ "$1" = "" ]
then
	vimdiff exfe.json exfe.json.example
fi

for i in service queue bot
do
	service exfe_$i stop
done

sleep 1s

for i in service queue bot
do
	service exfe_$i start
done
